nginx-json-check:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET "/status.json" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000

nginx-html-check:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000